/**
 * @file constants.js
 * @description Central constants for the Hostel Alert & Automation Module.
 *
 * WHY: Centralizing all magic strings/enums in one place ensures consistency
 * across models, services, handlers, and socket events. Any new alert type
 * is added here once and automatically available everywhere.
 */

'use strict';

// ─────────────────────────────────────────────
// ALERT TYPES
// Fine-grained event types that describe exactly what happened.
// Used in HostelAlert.type and event emitter payloads.
// ─────────────────────────────────────────────
const ALERT_TYPES = {
  // Attendance
  STUDENT_PRESENT: 'STUDENT_PRESENT',
  STUDENT_ABSENT: 'STUDENT_ABSENT',
  ATTENDANCE_MISSING: 'ATTENDANCE_MISSING',
  ATTENDANCE_UPDATED: 'ATTENDANCE_UPDATED',
  ATTENDANCE_CORRECTION: 'ATTENDANCE_CORRECTION',
  CONSECUTIVE_ABSENCE: 'CONSECUTIVE_ABSENCE',
  LOW_ATTENDANCE_PERCENTAGE: 'LOW_ATTENDANCE_PERCENTAGE',

  // Check-In / Check-Out
  CHECKIN: 'CHECKIN',
  CHECKOUT: 'CHECKOUT',
  LATE_CHECKIN: 'LATE_CHECKIN',
  UNAUTHORIZED_CHECKOUT: 'UNAUTHORIZED_CHECKOUT',
  DUPLICATE_CHECKIN: 'DUPLICATE_CHECKIN',
  DUPLICATE_CHECKOUT: 'DUPLICATE_CHECKOUT',
  STUDENT_OUTSIDE_HOSTEL: 'STUDENT_OUTSIDE_HOSTEL',
  NEVER_CHECKED_BACK_IN: 'NEVER_CHECKED_BACK_IN',

  // Leave Management
  LEAVE_REQUESTED: 'LEAVE_REQUESTED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',
  LEAVE_EXPIRED: 'LEAVE_EXPIRED',
  LEAVE_OVERDUE: 'LEAVE_OVERDUE',
  LEFT_WITHOUT_LEAVE: 'LEFT_WITHOUT_LEAVE',

  // Curfew
  CURFEW_VIOLATION: 'CURFEW_VIOLATION',
  CURFEW_CHECK_COMPLETE: 'CURFEW_CHECK_COMPLETE',
  MISSED_MANDATORY_CHECKIN: 'MISSED_MANDATORY_CHECKIN',

  // Occupancy
  OCCUPANCY_LIMIT_EXCEEDED: 'OCCUPANCY_LIMIT_EXCEEDED',
  INVALID_OCCUPANCY: 'INVALID_OCCUPANCY',
  ROOM_ASSIGNMENT_CONFLICT: 'ROOM_ASSIGNMENT_CONFLICT',

  // Emergency
  EMERGENCY_FIRE: 'EMERGENCY_FIRE',
  EMERGENCY_MEDICAL: 'EMERGENCY_MEDICAL',
  EMERGENCY_SECURITY: 'EMERGENCY_SECURITY',
  EMERGENCY_NATURAL_DISASTER: 'EMERGENCY_NATURAL_DISASTER',
  EMERGENCY_EVACUATION: 'EMERGENCY_EVACUATION',
  EMERGENCY_OTHER: 'EMERGENCY_OTHER',

  // Hostel Operations
  MAINTENANCE_REQUEST: 'MAINTENANCE_REQUEST',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  DISCIPLINE: 'DISCIPLINE',
};

// ─────────────────────────────────────────────
// ALERT CATEGORIES
// Broad groupings for filtering and display.
// ─────────────────────────────────────────────
const ALERT_CATEGORIES = {
  ATTENDANCE: 'attendance',
  CHECKIN: 'checkin',
  CHECKOUT: 'checkout',
  LEAVE: 'leave',
  CURFEW: 'curfew',
  EMERGENCY: 'emergency',
  SECURITY: 'security',
  HOSTEL_OPERATIONS: 'hostel_operations',
  MAINTENANCE: 'maintenance',
  ANNOUNCEMENT: 'announcement',
  DISCIPLINE: 'discipline',
  OCCUPANCY: 'occupancy',
};

// Maps each alert type to its category (for automatic categorisation)
const ALERT_TYPE_TO_CATEGORY = {
  [ALERT_TYPES.STUDENT_PRESENT]: ALERT_CATEGORIES.ATTENDANCE,
  [ALERT_TYPES.STUDENT_ABSENT]: ALERT_CATEGORIES.ATTENDANCE,
  [ALERT_TYPES.ATTENDANCE_MISSING]: ALERT_CATEGORIES.ATTENDANCE,
  [ALERT_TYPES.ATTENDANCE_UPDATED]: ALERT_CATEGORIES.ATTENDANCE,
  [ALERT_TYPES.ATTENDANCE_CORRECTION]: ALERT_CATEGORIES.ATTENDANCE,
  [ALERT_TYPES.CONSECUTIVE_ABSENCE]: ALERT_CATEGORIES.ATTENDANCE,
  [ALERT_TYPES.LOW_ATTENDANCE_PERCENTAGE]: ALERT_CATEGORIES.ATTENDANCE,

  [ALERT_TYPES.CHECKIN]: ALERT_CATEGORIES.CHECKIN,
  [ALERT_TYPES.LATE_CHECKIN]: ALERT_CATEGORIES.CHECKIN,
  [ALERT_TYPES.DUPLICATE_CHECKIN]: ALERT_CATEGORIES.CHECKIN,
  [ALERT_TYPES.CHECKOUT]: ALERT_CATEGORIES.CHECKOUT,
  [ALERT_TYPES.UNAUTHORIZED_CHECKOUT]: ALERT_CATEGORIES.CHECKOUT,
  [ALERT_TYPES.DUPLICATE_CHECKOUT]: ALERT_CATEGORIES.CHECKOUT,
  [ALERT_TYPES.STUDENT_OUTSIDE_HOSTEL]: ALERT_CATEGORIES.CHECKOUT,
  [ALERT_TYPES.NEVER_CHECKED_BACK_IN]: ALERT_CATEGORIES.CHECKOUT,

  [ALERT_TYPES.LEAVE_REQUESTED]: ALERT_CATEGORIES.LEAVE,
  [ALERT_TYPES.LEAVE_APPROVED]: ALERT_CATEGORIES.LEAVE,
  [ALERT_TYPES.LEAVE_REJECTED]: ALERT_CATEGORIES.LEAVE,
  [ALERT_TYPES.LEAVE_CANCELLED]: ALERT_CATEGORIES.LEAVE,
  [ALERT_TYPES.LEAVE_EXPIRED]: ALERT_CATEGORIES.LEAVE,
  [ALERT_TYPES.LEAVE_OVERDUE]: ALERT_CATEGORIES.LEAVE,
  [ALERT_TYPES.LEFT_WITHOUT_LEAVE]: ALERT_CATEGORIES.LEAVE,

  [ALERT_TYPES.CURFEW_VIOLATION]: ALERT_CATEGORIES.CURFEW,
  [ALERT_TYPES.CURFEW_CHECK_COMPLETE]: ALERT_CATEGORIES.CURFEW,
  [ALERT_TYPES.MISSED_MANDATORY_CHECKIN]: ALERT_CATEGORIES.CURFEW,

  [ALERT_TYPES.OCCUPANCY_LIMIT_EXCEEDED]: ALERT_CATEGORIES.OCCUPANCY,
  [ALERT_TYPES.INVALID_OCCUPANCY]: ALERT_CATEGORIES.OCCUPANCY,
  [ALERT_TYPES.ROOM_ASSIGNMENT_CONFLICT]: ALERT_CATEGORIES.OCCUPANCY,

  [ALERT_TYPES.EMERGENCY_FIRE]: ALERT_CATEGORIES.EMERGENCY,
  [ALERT_TYPES.EMERGENCY_MEDICAL]: ALERT_CATEGORIES.EMERGENCY,
  [ALERT_TYPES.EMERGENCY_SECURITY]: ALERT_CATEGORIES.EMERGENCY,
  [ALERT_TYPES.EMERGENCY_NATURAL_DISASTER]: ALERT_CATEGORIES.EMERGENCY,
  [ALERT_TYPES.EMERGENCY_EVACUATION]: ALERT_CATEGORIES.EMERGENCY,
  [ALERT_TYPES.EMERGENCY_OTHER]: ALERT_CATEGORIES.EMERGENCY,

  [ALERT_TYPES.MAINTENANCE_REQUEST]: ALERT_CATEGORIES.MAINTENANCE,
  [ALERT_TYPES.ANNOUNCEMENT]: ALERT_CATEGORIES.ANNOUNCEMENT,
  [ALERT_TYPES.DISCIPLINE]: ALERT_CATEGORIES.DISCIPLINE,
};

// ─────────────────────────────────────────────
// ALERT PRIORITIES
// Controls display order and push notification priority.
// ─────────────────────────────────────────────
const ALERT_PRIORITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  URGENT: 'urgent',
  CRITICAL: 'critical',
};

// Default priority for each alert type
const ALERT_TYPE_PRIORITY = {
  [ALERT_TYPES.EMERGENCY_FIRE]: ALERT_PRIORITY.CRITICAL,
  [ALERT_TYPES.EMERGENCY_MEDICAL]: ALERT_PRIORITY.CRITICAL,
  [ALERT_TYPES.EMERGENCY_SECURITY]: ALERT_PRIORITY.CRITICAL,
  [ALERT_TYPES.EMERGENCY_NATURAL_DISASTER]: ALERT_PRIORITY.CRITICAL,
  [ALERT_TYPES.EMERGENCY_EVACUATION]: ALERT_PRIORITY.CRITICAL,
  [ALERT_TYPES.EMERGENCY_OTHER]: ALERT_PRIORITY.URGENT,

  [ALERT_TYPES.CURFEW_VIOLATION]: ALERT_PRIORITY.HIGH,
  [ALERT_TYPES.LEFT_WITHOUT_LEAVE]: ALERT_PRIORITY.HIGH,
  [ALERT_TYPES.LEAVE_OVERDUE]: ALERT_PRIORITY.HIGH,
  [ALERT_TYPES.UNAUTHORIZED_CHECKOUT]: ALERT_PRIORITY.HIGH,
  [ALERT_TYPES.NEVER_CHECKED_BACK_IN]: ALERT_PRIORITY.HIGH,
  [ALERT_TYPES.CONSECUTIVE_ABSENCE]: ALERT_PRIORITY.HIGH,

  [ALERT_TYPES.STUDENT_ABSENT]: ALERT_PRIORITY.MEDIUM,
  [ALERT_TYPES.ATTENDANCE_MISSING]: ALERT_PRIORITY.MEDIUM,
  [ALERT_TYPES.LATE_CHECKIN]: ALERT_PRIORITY.MEDIUM,
  [ALERT_TYPES.LEAVE_EXPIRED]: ALERT_PRIORITY.MEDIUM,
  [ALERT_TYPES.OCCUPANCY_LIMIT_EXCEEDED]: ALERT_PRIORITY.MEDIUM,

  [ALERT_TYPES.LEAVE_REQUESTED]: ALERT_PRIORITY.LOW,
  [ALERT_TYPES.LEAVE_APPROVED]: ALERT_PRIORITY.LOW,
  [ALERT_TYPES.LEAVE_REJECTED]: ALERT_PRIORITY.LOW,
  [ALERT_TYPES.STUDENT_PRESENT]: ALERT_PRIORITY.LOW,
  [ALERT_TYPES.ANNOUNCEMENT]: ALERT_PRIORITY.LOW,
};

// ─────────────────────────────────────────────
// ROLES
// Mirrors User.role enum for consistency.
// ─────────────────────────────────────────────
const ROLES = {
  STUDENT: 'student',
  WARDEN: 'warden',
  OWNER: 'owner',
  SECURITY: 'security',
  SUPERADMIN: 'superadmin',
  SUPERVISOR: 'supervisor',
  CLEANER: 'cleaner',
};

// Roles that manage hostels (receive warden-level alerts)
const HOSTEL_MANAGER_ROLES = [ROLES.WARDEN, ROLES.OWNER];
const ADMIN_ROLES = [ROLES.OWNER, ROLES.SUPERADMIN];
const ALL_STAFF_ROLES = [ROLES.WARDEN, ROLES.OWNER, ROLES.SECURITY, ROLES.SUPERADMIN];

// ─────────────────────────────────────────────
// ALERT STATUS
// Lifecycle states for a HostelAlert document.
// ─────────────────────────────────────────────
const ALERT_STATUS = {
  UNREAD: 'unread',
  READ: 'read',
  RESOLVED: 'resolved',
  DISMISSED: 'dismissed',
};

// ─────────────────────────────────────────────
// SOCKET EVENTS
// All real-time event names emitted via Socket.IO.
// WHY: Centralising socket event names prevents typo bugs across client/server.
// ─────────────────────────────────────────────
const SOCKET_EVENTS = {
  // Server → Client
  NEW_ALERT: 'alert:new',
  ALERT_RESOLVED: 'alert:resolved',
  ALERT_READ: 'alert:read',
  CURFEW_VIOLATION: 'curfew:violation',
  CURFEW_CHECK_DONE: 'curfew:check_done',
  EMERGENCY_BROADCAST: 'emergency:broadcast',
  OCCUPANCY_UPDATE: 'occupancy:update',
  CHECKIN_EVENT: 'gate:checkin',
  CHECKOUT_EVENT: 'gate:checkout',
  LEAVE_STATUS_CHANGE: 'leave:status',
  ATTENDANCE_UPDATE: 'attendance:update',

  // Client → Server
  JOIN_HOSTEL_ROOM: 'join:hostel',
  JOIN_ROLE_ROOM: 'join:role',
  LEAVE_ROOM: 'leave:room',
  PING: 'ping',

  // System
  CONNECTED: 'connected',
  DISCONNECTED: 'disconnected',
  ERROR: 'error',
};

// ─────────────────────────────────────────────
// QUEUE NAMES (BullMQ)
// ─────────────────────────────────────────────
const QUEUE_NAMES = {
  ALERTS: 'hostel-alerts',
  CURFEW_CHECK: 'curfew-check',
  ATTENDANCE_CHECK: 'attendance-check',
  LEAVE_EXPIRY: 'leave-expiry',
  DEAD_LETTER: 'alert-dlq',
};

// ─────────────────────────────────────────────
// JOB NAMES (BullMQ job types)
// ─────────────────────────────────────────────
const JOB_NAMES = {
  DAILY_CURFEW_CHECK: 'daily-curfew-check',
  DAILY_ATTENDANCE_CHECK: 'daily-attendance-check',
  LEAVE_EXPIRY_CHECK: 'leave-expiry-check',
  SEND_PUSH_NOTIFICATION: 'send-push-notification',
  RETRY_FAILED_ALERT: 'retry-failed-alert',
};

// ─────────────────────────────────────────────
// AUTOMATION THRESHOLDS (configurable defaults)
// These are defaults; production values should come from hostel settings.
// ─────────────────────────────────────────────
const THRESHOLDS = {
  CONSECUTIVE_ABSENCE_ALERT: 2,       // Alert after N consecutive absences
  LOW_ATTENDANCE_PERCENT: 75,          // Alert when attendance drops below this %
  CURFEW_GRACE_PERIOD_MINUTES: 15,     // Grace period after curfew time
  LEAVE_OVERDUE_THRESHOLD_HOURS: 2,    // How long after leave end to escalate
};

module.exports = {
  ALERT_TYPES,
  ALERT_CATEGORIES,
  ALERT_TYPE_TO_CATEGORY,
  ALERT_PRIORITY,
  ALERT_TYPE_PRIORITY,
  ROLES,
  HOSTEL_MANAGER_ROLES,
  ADMIN_ROLES,
  ALL_STAFF_ROLES,
  ALERT_STATUS,
  SOCKET_EVENTS,
  QUEUE_NAMES,
  JOB_NAMES,
  THRESHOLDS,
};
